// Generated by CoffeeScript 1.6.3
var app;

app = app || {};

app.AppView = Backbone.View.extend({
  el: '#todoapp',
  statsTemplate: _.template($('#statsTemplate').html()),
  events: {
    'keypress #new-todo': 'createOnEnter',
    'click #clear-completed': 'clearCompleted',
    'click #toggle-all': 'toggleAllComplete'
  },
  initialization: function() {
    this.allCheckbox = this.$('#toggle-all')[0];
    this.$input = this.$('#new-todo');
    this.$footer = this.$('#footer');
    this.$main = $('#main');
    this.listenTo(app.Todos, 'add', this.addOne);
    this.listenTo(app.Todos, 'reset', this.addAll);
  },
  addOne: function() {
    var view;
    view = new app.TodoView(model.Todo);
    $('#todo-list').append(view.render().el);
  },
  addAll: function() {
    this.$('#todo-list').html('');
    app.Todos.each(this.addOne, this);
  }
});
