// Generated by CoffeeScript 1.6.3
var app;

app = app || {};

app.Todo = Backbone.Model.extend({
  defaults: {
    title: "",
    completed: false
  },
  toggle: function() {
    return this.save({
      completed: !this.get("completed")
    });
  }
});
